<a href="https://colab.research.google.com/github/justinsantacruz/MAT494/blob/main/Mean_Vector_and_Covariance_Matrix.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
np.random.seed(1234)
A = np.random.normal(size=(5,5))
A = A @ A.T

with np.printoptions(precision=3, suppress=True):
    print(A)
    
print()
L = np.linalg.cholesky(A)
#print(L)

with np.printoptions(precision=3, suppress=True):
    print(L @ L.T)
    
b = np.random.normal(size=(5,1))
print(b)

[[ 4.31   0.094  1.599  0.634 -0.16 ]
 [ 0.094  6.961  1.984  3.656 -3.814]
 [ 1.599  1.984  7.412 -1.473 -2.258]
 [ 0.634  3.656 -1.473  4.386 -1.518]
 [-0.16  -3.814 -2.258 -1.518  2.553]]

[[ 4.31   0.094  1.599  0.634 -0.16 ]
 [ 0.094  6.961  1.984  3.656 -3.814]
 [ 1.599  1.984  7.412 -1.473 -2.258]
 [ 0.634  3.656 -1.473  4.386 -1.518]
 [-0.16  -3.814 -2.258 -1.518  2.553]]
[[-0.46930528]
 [ 0.67555409]
 [-1.81702723]
 [-0.18310854]
 [ 1.05896919]]


In [3]:
np.random.seed(20)

X = np.random.normal(size = (10000,))
Y = np.random.normal(size = (10000,))

C = np.array([[1, 0.5], [0.5, 1]])

X.shape = (1, X.size)
Y.shape = (1, Y.size)

XY = np.vstack((X, Y))

L = np.linalg.cholesky(C)

UV = L @ XY

U = UV[0, :]
V = UV[1, :]

print(np.cov(U,V))

[[1.00049833 0.4895314 ]
 [0.4895314  1.00321852]]
